apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argoapp1
  namespace: samosa
spec:
  destination:
    namespace: samosa
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: /
    repoURL: https://github.com/kharatramesh/argocd1
    targetRevision: k8s
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
